"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,Upload,ImagePlus,LockKeyhole,RotateCcw} from "lucide-react";
const key="gunavathi-products";
const defaults=[
{name:"Premium Cotton Saree",price:"₹899",image:"https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85"},
{name:"Traditional Silk Saree",price:"₹1,999",image:"https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=90"},
{name:"Men's Veshti",price:"₹499",image:"https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85"},
{name:"Daily Wear Fabric",price:"₹299",image:"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85"}];
export default function Admin(){
 const [ok,setOk]=useState(false),[pass,setPass]=useState(""),[products,setProducts]=useState(defaults),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState("");
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const s=localStorage.getItem(key);if(s)setProducts(JSON.parse(s))}catch{}},[]);
 const login=()=>pass==="gunavathi123"?setOk(true):setMessage("Incorrect admin password.");
 const save=(next:any[])=>{setProducts(next);localStorage.setItem(key,JSON.stringify(next));setMessage("Image saved successfully.");};
 const choose=(i:number)=>{setSelected(i);input.current?.click()};
 const upload=(file:File)=>{if(selected===null)return;if(!file.type.startsWith("image/"))return setMessage("Please select an image file.");if(file.size>2*1024*1024)return setMessage("Please use an image below 2 MB.");const r=new FileReader();r.onload=()=>{const next=[...products];next[selected]={...next[selected],image:String(r.result)};save(next)};r.readAsDataURL(file)};
 if(!ok)return <main className="min-h-screen bg-cream grid place-items-center px-5"><div className="w-full max-w-md bg-white rounded-3xl shadow-xl p-8 border border-black/5"><div className="w-14 h-14 rounded-full bg-brand text-white grid place-items-center mx-auto"><LockKeyhole/></div><h1 className="font-serif text-3xl text-center mt-5">Gunavathi Tex Admin</h1><p className="text-center text-black/50 mt-2">Manage your textile images</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Admin password" className="w-full mt-7 border rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-brand"/>{message&&<p className="text-red-600 text-sm mt-3">{message}</p>}<button onClick={login} className="w-full mt-4 bg-brand text-white rounded-xl py-3 font-bold">Enter Admin Panel</button><a href="/" className="block text-center mt-5 text-brand text-sm">← Back to website</a></div></main>;
 return <main className="min-h-screen bg-cream"><header className="bg-deep text-white"><div className="max-w-6xl mx-auto px-5 py-5 flex justify-between items-center"><div><p className="text-gold text-xs tracking-[.2em] uppercase">Gunavathi Tex</p><h1 className="font-serif text-2xl">Admin Panel</h1></div><a href="/" className="flex items-center gap-2 border border-white/20 rounded-full px-4 py-2 text-sm"><ArrowLeft size={16}/> Website</a></div></header><div className="max-w-6xl mx-auto px-5 py-10"><div className="bg-white rounded-2xl p-5 mb-7 border border-black/5"><h2 className="font-serif text-2xl">Upload product images</h2><p className="text-sm text-black/55 mt-1">Select a product, upload an image, and it will immediately update the website on this browser.</p></div>{message&&<div className="mb-5 bg-green-50 text-green-800 rounded-xl p-4 text-sm">{message}</div>}<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{products.map((p,i)=><article key={p.name} className="bg-white rounded-2xl overflow-hidden border border-black/5 shadow-sm"><div className="relative"><img src={p.image} alt={p.name} className="w-full h-64 object-cover"/><button onClick={()=>choose(i)} className="absolute bottom-3 right-3 bg-brand text-white rounded-full p-3 shadow-lg" title="Upload image"><Upload size={18}/></button></div><div className="p-5"><h3 className="font-serif text-lg">{p.name}</h3><p className="text-brand font-bold mt-1">{p.price}</p><button onClick={()=>choose(i)} className="mt-4 w-full border border-brand text-brand rounded-xl py-2.5 font-semibold flex justify-center items-center gap-2"><ImagePlus size={17}/> Upload / Replace Image</button><button onClick={()=>save(products.map((x,j)=>j===i?{...x,image:defaults[i].image}:x))} className="mt-2 w-full text-sm text-black/50 hover:text-brand flex justify-center items-center gap-1"><RotateCcw size={14}/> Restore default</button></div></article>)}</div><input ref={input} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/><p className="text-xs text-black/45 mt-8">Maximum image size: 2 MB. This first version stores uploaded images in browser storage.</p></div></main>
}