"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,MapPin,Phone,MessageCircle,ShoppingBag,Star,Truck,ShieldCheck,Instagram,LockKeyhole,Search,X,Plus,Minus,ChevronDown} from "lucide-react";

type Product={name:string;price:string;unit:string;category:string;description:string;image:string};
const defaults:Product[]=[
{name:"Cotton Name Tape",price:"₹120",unit:"per roll",category:"Name Tapes",description:"Durable woven name tapes for school uniforms, garments, bags and custom labelling.",image:"https://images.unsplash.com/photo-1523381294911-8d3cead13475?auto=format&fit=crop&w=1000&q=85"},
{name:"Custom Printed Name Tape",price:"₹180",unit:"per roll",category:"Name Tapes",description:"Custom name tapes with your required text, colour and finish.",image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=85"},
{name:"Woven Name Rope",price:"₹250",unit:"per bundle",category:"Name Ropes",description:"Strong woven name ropes and textile cords for garment and identification applications.",image:"https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1000&q=85"},
{name:"Custom Textile Labels",price:"₹300",unit:"per order",category:"Labels",description:"Made-to-order textile labels for schools, businesses and garment units.",image:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85"},
{name:"Uniform Name Labels",price:"₹220",unit:"per set",category:"Labels",description:"Neat personalised labels designed for school and work uniforms.",image:"https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=1000&q=85"},
{name:"Premium Woven Tape",price:"₹240",unit:"per roll",category:"Name Tapes",description:"Premium woven identification tape for durable everyday garment use.",image:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85"}
];
const waNumber="918610732094";
const wa=(text:string)=>`https://wa.me/${waNumber}?text=${encodeURIComponent(text)}`;

export default function Home(){
 const [products,setProducts]=useState<Product[]>(defaults),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[bag,setBag]=useState<string[]>([]),[showBag,setShowBag]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("gunavathi-products");if(saved)setProducts(JSON.parse(saved))}catch{}},[]);
 const categories=["All",...Array.from(new Set(products.map(p=>p.category)))];
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&(p.name+" "+p.description).toLowerCase().includes(query.toLowerCase())),[products,category,query]);
 const hero=products[1]?.image||defaults[1].image;
 const enquire=(items:string[])=>wa(`Hello Gunavathi Tex, I would like to enquire about: ${items.join(", ")}. Please share price, available colours, minimum quantity and delivery details.`);
 return <main className="min-h-screen bg-cream">
 <div className="bg-deep text-white text-center text-xs tracking-[.12em] py-2.5">CUSTOM TEXTILES • BULK ORDERS • KOMARAPALAYAM • WHATSAPP ORDERS</div>
 <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-black/5">
  <div className="max-w-7xl mx-auto px-5 h-20 flex items-center justify-between gap-5">
   <a href="#" className="flex items-center gap-3 shrink-0"><div className="w-11 h-11 rounded-full bg-brand text-white grid place-items-center font-serif text-xl">G</div><div><div className="font-serif text-xl font-bold text-brand">Gunavathi Tex</div><div className="text-[9px] tracking-[.22em] uppercase text-deep/55">Gunavathi Devi Textiles</div></div></a>
   <nav className="hidden lg:flex items-center gap-7 text-sm font-semibold"><a href="#collections" className="hover:text-brand">Collections</a><a href="#custom" className="hover:text-brand">Custom Orders</a><a href="#about" className="hover:text-brand">Our Story</a><a href="#contact" className="hover:text-brand">Contact</a></nav>
   <div className="flex items-center gap-2"><button onClick={()=>setShowBag(true)} className="relative border rounded-full p-3 hover:border-brand"><ShoppingBag size={18}/>{bag.length>0&&<span className="absolute -top-1 -right-1 bg-brand text-white text-[10px] w-5 h-5 rounded-full grid place-items-center">{bag.length}</span>}</button><a href={wa("Hello Gunavathi Tex, I would like to enquire about your textile products.")} target="_blank" rel="noreferrer" className="hidden sm:inline-flex bg-brand text-white px-5 py-2.5 rounded-full font-semibold">WhatsApp Us</a></div>
  </div>
 </header>

 <section className="bg-deep text-white overflow-hidden">
  <div className="max-w-7xl mx-auto px-5 py-14 md:py-24 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
   <div className="reveal"><p className="text-gold font-bold tracking-[.25em] uppercase text-xs mb-5">Woven with care • Made for you</p><h1 className="font-serif text-5xl md:text-7xl leading-[.92]">Textiles that carry <span className="text-gold">your name.</span></h1><p className="mt-7 text-white/70 text-lg max-w-xl leading-8">Quality name tapes, woven ropes and custom textile labels for uniforms, garments, schools, businesses and bulk requirements.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#collections" className="bg-gold text-deep font-bold px-6 py-3.5 rounded-full inline-flex items-center gap-2">Explore Collection <ArrowRight size={18}/></a><a href={wa("Hello Gunavathi Tex, I need a custom textile order.")} target="_blank" rel="noreferrer" className="border border-white/25 px-6 py-3.5 rounded-full inline-flex items-center gap-2"><MessageCircle size={18}/> Custom Enquiry</a></div><div className="mt-10 flex flex-wrap gap-6 text-xs text-white/60"><span>✓ Custom text</span><span>✓ Bulk quantities</span><span>✓ Direct support</span></div></div>
   <div className="relative"><div className="absolute -inset-4 bg-gold/10 rounded-[2rem] rotate-2"></div><div className="relative overflow-hidden rounded-[2rem] border border-white/10"><img src={hero} alt="Gunavathi Tex textile collection" className="w-full h-[430px] object-cover"/><div className="absolute bottom-5 left-5 right-5 bg-white/90 text-deep backdrop-blur rounded-2xl p-4 flex justify-between items-center"><div><p className="text-[10px] uppercase tracking-widest text-brand font-bold">Featured</p><b>Custom Printed Name Tape</b></div><span className="font-serif text-xl">₹180</span></div></div></div>
  </div>
 </section>

 <section className="bg-white border-b"><div className="max-w-7xl mx-auto px-5 py-7 grid grid-cols-2 md:grid-cols-4 gap-6"><div className="flex gap-3 items-center"><ShoppingBag className="text-brand"/><div><b className="block text-sm">Curated Collection</b><span className="text-xs text-black/45">Useful textile products</span></div></div><div className="flex gap-3 items-center"><ShieldCheck className="text-brand"/><div><b className="block text-sm">Quality Focused</b><span className="text-xs text-black/45">Made for daily use</span></div></div><div className="flex gap-3 items-center"><Truck className="text-brand"/><div><b className="block text-sm">Bulk Friendly</b><span className="text-xs text-black/45">Schools & businesses</span></div></div><div className="flex gap-3 items-center"><Star className="text-brand"/><div><b className="block text-sm">Direct Service</b><span className="text-xs text-black/45">Talk to us directly</span></div></div></div></section>

 <section id="collections" className="max-w-7xl mx-auto px-5 py-20">
  <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10"><div><p className="text-brand uppercase tracking-[.2em] text-xs font-bold">The collection</p><h2 className="font-serif text-4xl md:text-5xl mt-2">Find your textile</h2><p className="text-black/50 mt-2">Browse products and send your selected items as one enquiry.</p></div><div className="relative w-full md:w-72"><Search className="absolute left-4 top-3.5 text-black/35" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." className="w-full bg-white border border-black/10 rounded-full pl-11 pr-4 py-3 outline-none focus:border-brand"/></div></div>
  <div className="flex gap-2 overflow-x-auto pb-3 mb-8">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`px-5 py-2.5 rounded-full text-sm font-semibold whitespace-nowrap transition ${category===c?"bg-brand text-white":"bg-white border border-black/10 hover:border-brand"}`}>{c}</button>)}</div>
  {filtered.length===0?<div className="bg-white rounded-3xl p-12 text-center">No products found. Try another search.</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-7">{filtered.map((p,i)=><article key={p.name} className="group bg-white rounded-3xl overflow-hidden border border-black/5 shadow-sm hover:-translate-y-1 hover:shadow-xl transition duration-300"><div className="relative overflow-hidden"><img src={p.image} alt={p.name} className="w-full h-80 object-cover group-hover:scale-105 transition duration-700"/><span className="absolute top-4 left-4 bg-white/90 backdrop-blur px-3 py-1.5 rounded-full text-[10px] uppercase tracking-wider font-bold text-brand">{p.category}</span><button onClick={()=>setBag(b=>b.includes(p.name)?b.filter(x=>x!==p.name):[...b,p.name])} className={`absolute top-4 right-4 w-10 h-10 rounded-full grid place-items-center shadow ${bag.includes(p.name)?"bg-brand text-white":"bg-white/90 text-deep"}`}><ShoppingBag size={17}/></button></div><div className="p-6"><h3 className="font-serif text-2xl">{p.name}</h3><p className="text-sm text-black/55 mt-2 leading-6 min-h-12">{p.description}</p><div className="mt-5 flex items-center justify-between"><div><span className="font-bold text-xl text-deep">{p.price}</span><span className="text-xs text-black/40 ml-1">{p.unit}</span></div><a href={wa(`Hello Gunavathi Tex, I am interested in ${p.name}. Please share details.`)} target="_blank" rel="noreferrer" className="text-sm font-bold text-brand">Enquire →</a></div></div></article>)}</div>}
 </section>

 <section id="custom" className="bg-deep text-white"><div className="max-w-7xl mx-auto px-5 py-20 grid md:grid-cols-2 gap-14 items-center"><div><p className="text-gold uppercase tracking-[.2em] text-xs font-bold">Custom textile service</p><h2 className="font-serif text-4xl md:text-5xl mt-3">Have a specific name, size or colour?</h2><p className="text-white/65 mt-6 leading-8">Tell us what you need. We can discuss text, dimensions, colours, quantity and finish for your requirement before you place the order.</p><a href={wa("Hello Gunavathi Tex, I have a custom textile requirement. Please guide me.")} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 bg-gold text-deep px-6 py-3.5 rounded-full font-bold">Start Custom Enquiry <ArrowRight size={18}/></a></div><div className="grid grid-cols-2 gap-4"><div className="zari-frame p-6 rounded-3xl"><b className="text-xl">01</b><p className="mt-8 font-semibold">Share your text</p><p className="text-sm text-white/50 mt-2">Name, brand or identification text.</p></div><div className="zari-frame p-6 rounded-3xl"><b className="text-xl">02</b><p className="mt-8 font-semibold">Choose details</p><p className="text-sm text-white/50 mt-2">Size, colour, quantity and finish.</p></div><div className="zari-frame p-6 rounded-3xl"><b className="text-xl">03</b><p className="mt-8 font-semibold">Get a quote</p><p className="text-sm text-white/50 mt-2">We discuss your requirement directly.</p></div><div className="zari-frame p-6 rounded-3xl"><b className="text-xl">04</b><p className="mt-8 font-semibold">Confirm order</p><p className="text-sm text-white/50 mt-2">Proceed once the details are agreed.</p></div></div></div></section>

 <section id="about" className="max-w-7xl mx-auto px-5 py-20 grid md:grid-cols-2 gap-14 items-center"><div><p className="text-brand uppercase tracking-[.2em] text-xs font-bold">About Gunavathi Tex</p><h2 className="font-serif text-4xl md:text-5xl mt-3 leading-tight">A local textile brand with a personal touch.</h2><p className="mt-6 text-black/60 leading-8">Gunavathi Tex (Gunavathi Devi Textiles), based in Komarapalayam, serves customers looking for name tapes, name ropes and custom textile identification products.</p><p className="mt-4 text-black/60 leading-8">The website is designed to make discovery simple while keeping custom ordering direct and personal through WhatsApp.</p></div><div className="bg-cream rounded-[2rem] p-8 md:p-12"><p className="text-brand font-bold text-sm tracking-widest">GOOD FOR</p><div className="mt-7 grid grid-cols-2 gap-6">{["Schools","Garment Units","Businesses","Institutions","Bulk Orders","Custom Labels"].map(x=><div key={x} className="bg-white rounded-2xl p-5 font-semibold">{x}</div>)}</div></div></section>

 <section id="contact" className="max-w-7xl mx-auto px-5 pb-20"><div className="bg-brand rounded-[2rem] text-white p-8 md:p-14 grid md:grid-cols-2 gap-10 items-center"><div><p className="text-gold uppercase tracking-[.2em] text-xs font-bold">Visit or contact us</p><h2 className="font-serif text-4xl md:text-5xl mt-3">Ready to discuss your order?</h2><p className="mt-5 text-white/70 leading-7">For pricing, custom requirements, bulk orders and availability, contact Gunavathi Tex directly.</p></div><div className="space-y-5 text-sm"><div className="flex gap-4"><MapPin className="text-gold"/><div><b>Location</b><p className="text-white/70 mt-1">Komarapalayam, Tamil Nadu, India</p></div></div><div className="flex gap-4"><Phone className="text-gold"/><div><b>Phone / WhatsApp</b><p className="text-white/70 mt-1">+91 86107 32094</p></div></div><div className="flex gap-4"><Instagram className="text-gold"/><div><b>Social</b><p className="text-white/70 mt-1">Gunavathi Tex textile updates</p></div></div><a href={wa("Hello Gunavathi Tex, I would like to place an enquiry.")} target="_blank" rel="noreferrer" className="bg-white text-brand px-6 py-3 rounded-full inline-flex items-center gap-2 font-bold"><MessageCircle size={18}/> Chat on WhatsApp</a></div></div></section>

 <footer className="bg-deep text-white/55"><div className="max-w-7xl mx-auto px-5 py-9 flex flex-col md:flex-row justify-between gap-4 text-sm"><span>© {new Date().getFullYear()} Gunavathi Tex. All rights reserved.</span><div className="flex gap-5"><a href="/admin" className="hover:text-white flex items-center gap-1"><LockKeyhole size={13}/> Admin</a><span>Gunavathi Devi Textiles • Komarapalayam</span></div></div></footer>

 {showBag&&<div className="fixed inset-0 z-[70] bg-black/40 backdrop-blur-sm" onClick={()=>setShowBag(false)}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-md bg-white shadow-2xl p-6 flex flex-col"><div className="flex justify-between items-center"><div><p className="text-brand text-xs uppercase tracking-widest font-bold">Your enquiry</p><h2 className="font-serif text-3xl mt-1">Selected products</h2></div><button onClick={()=>setShowBag(false)} className="p-2 rounded-full hover:bg-cream"><X/></button></div><div className="flex-1 overflow-auto mt-8">{bag.length===0?<div className="text-center text-black/45 py-20"><ShoppingBag className="mx-auto mb-4" size={34}/><p>Add products from the collection.</p></div>:<div className="space-y-3">{bag.map(name=><div key={name} className="flex items-center justify-between bg-cream rounded-2xl p-4"><span className="font-semibold">{name}</span><button onClick={()=>setBag(b=>b.filter(x=>x!==name))} className="text-black/40 hover:text-brand"><X size={18}/></button></div>)}</div>}</div><div className="border-t pt-5"><button disabled={!bag.length} onClick={()=>window.open(enquire(bag),"_blank")} className="w-full bg-brand disabled:opacity-40 text-white rounded-full py-3.5 font-bold flex justify-center items-center gap-2"><MessageCircle size={18}/> Send Enquiry on WhatsApp</button></div></aside></div>}
 </main>
}